name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install
      - name: Release
        env:
          GIT_AUTHOR_NAME: "oblakbot"
          GIT_AUTHOR_EMAIL: "sibin.grasic+bot@oblak.studio"
          GIT_COMMITTER_NAME: "oblakbot"
          GIT_COMMITTER_EMAIL: "sibin.grasic+bot@oblak.studio"
          GH_TOKEN: ${{ secrets.OBLAK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
